### ISSUE TITLE
hi,this project can manage mysql database?

### ISSUE THREAD

**Issue by youyizhongzhuangtaijiaofangkong** [madHEYsia/ClasssroomMail#1]

**Comment by madHEYsia** [comment]
Yes, I have made Dekstop apps (coded in Java) with mysql as Database. You can catch hold of these under Classroom Products:
https://github.com/madHEYsia/ClassroomWunderlist
https://github.com/madHEYsia/ClassroomDBMS
https://github.com/madHEYsia/ClassroomSlack
https://github.com/madHEYsia/ClassroomPopcorn

Also , if you want to manage mysql database through web. Visit https://github.com/madHEYsia/ClassroomAmazon 
(though I have started classroomAmazon and classroomMail few days back, so its not completed). Refer above 4 repositories for implementing.

**Comment by youyizhongzhuangtaijiaofangkong** [comment]
ok! Thank you!

At 2017-08-03 16:51:32, "Shubham Madheysia" <notifications@github.com> wrote:


Yes, I have made Dekstop apps (coded in Java) with mysql as Database. You can catch hold of these under Classroom Products:
https://github.com/madHEYsia/ClassroomWunderlist
https://github.com/madHEYsia/ClassroomDBMS
https://github.com/madHEYsia/ClassroomSlack
https://github.com/madHEYsia/ClassroomPopcorn

Also , if you want to manage mysql database through web. Visit https://github.com/madHEYsia/ClassroomAmazon
(though I have started classroomAmazon and classroomMail few days back, so its not completed). Refer above 4 repositories for implementing.
